# Generated by Django 5.2.2 on 2025-06-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_number', models.IntegerField()),
                ('article_title', models.CharField(max_length=100)),
                ('article_descr', models.CharField(default='', max_length=400)),
            ],
            options={
                'db_table': 'rest_articles',
            },
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('law_id', models.IntegerField(primary_key=True, serialize=False)),
                ('law_number', models.CharField(max_length=20, unique=True, verbose_name='Номер закона')),
                ('law_title', models.CharField(max_length=400, verbose_name='Название закона')),
                ('law_date', models.DateField(verbose_name='Дата принятия')),
            ],
            options={
                'db_table': 'rest_laws',
            },
        ),
        migrations.CreateModel(
            name='Responsibilitys',
            fields=[
                ('responsibility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('responsibility_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rest_responsibilitys',
            },
        ),
        migrations.CreateModel(
            name='ArticleClauses',
            fields=[
                ('clause_id', models.AutoField(primary_key=True, serialize=False)),
                ('clause_number', models.IntegerField(default=0)),
                ('clause_text', models.CharField(max_length=2000)),
                ('clause_parent_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='laws.articles')),
            ],
            options={
                'db_table': 'rest_articles_clauses',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='article_parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='laws.laws'),
        ),
        migrations.CreateModel(
            name='RespToArticles',
            fields=[
                ('resp_article_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('resp_first_type', models.IntegerField(default=0)),
                ('resp_second_type', models.IntegerField(default=0)),
                ('resp_third_type', models.IntegerField(default=0)),
                ('resp_fourth_type', models.IntegerField(default=0)),
                ('resp_another_type', models.IntegerField(default=0)),
                ('resp_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.articles')),
            ],
            options={
                'db_table': 'rest_resp_to_articles',
            },
        ),
        migrations.CreateModel(
            name='RespToLaws',
            fields=[
                ('resp_law_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resp_first_type', models.IntegerField(default=0)),
                ('resp_second_type', models.IntegerField(default=0)),
                ('resp_third_type', models.IntegerField(default=0)),
                ('resp_fourth_type', models.IntegerField(default=0)),
                ('resp_another_type', models.IntegerField(default=0)),
                ('resp_none_type', models.IntegerField(default=0)),
                ('resp_law_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.laws')),
            ],
            options={
                'db_table': 'rest_resp_to_laws',
            },
        ),
    ]
