# Generated by Django 5.2.2 on 2025-07-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laws',
            name='law_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
