# Generated by Django 5.2.2 on 2025-07-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_alter_laws_law_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='articles',
            unique_together={('article_parent_id', 'article_number')},
        ),
    ]
