# Generated by Django 5.2.2 on 2025-07-26 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0003_alter_articles_article_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclauses',
            name='clause_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='articleclauses',
            name='clause_parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.articles'),
        ),
    ]
