# Generated by Django 5.2.2 on 2025-07-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0004_alter_articleclauses_clause_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleclauses',
            unique_together={('clause_parent_id', 'clause_number')},
        ),
    ]
