# Generated by Django 5.2.2 on 2025-07-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0005_alter_articleclauses_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityTypes',
            fields=[
                ('responsibility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('responsibility_type', models.CharField(max_length=50)),
                ('responsibility_descr', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'rest_responsibility_types',
            },
        ),
        migrations.DeleteModel(
            name='Responsibilitys',
        ),
    ]
