# Generated by Django 5.1.7 on 2025-05-31 01:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_list',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessTypes',
            fields=[
                ('access_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('access_type_descr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'access_types',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_number', models.IntegerField()),
                ('article_title', models.CharField(max_length=100)),
                ('article_descr', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('law_id', models.IntegerField(primary_key=True, serialize=False)),
                ('law_number', models.CharField(max_length=20, unique=True, verbose_name='Номер закона')),
                ('law_title', models.CharField(max_length=400, verbose_name='Название закона')),
                ('law_date', models.DateField(verbose_name='Дата принятия')),
            ],
        ),
        migrations.CreateModel(
            name='MyClass1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data1', models.CharField(max_length=300)),
                ('data2', models.CharField(max_length=300)),
                ('data3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MyClass2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data1', models.CharField(max_length=300)),
                ('data2', models.CharField(max_length=300)),
                ('data3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibilitys',
            fields=[
                ('responsibility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('responsibility_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'users_info',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend_api.accesstypes'),
        ),
        migrations.CreateModel(
            name='ArticleClauses',
            fields=[
                ('clause_id', models.AutoField(primary_key=True, serialize=False)),
                ('clause_number', models.IntegerField(default=0)),
                ('clause_text', models.CharField(max_length=2000)),
                ('clause_parent_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend_api.articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='article_parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend_api.laws'),
        ),
        migrations.CreateModel(
            name='RespToArticles',
            fields=[
                ('resp_article_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('resp_first_type', models.IntegerField(default=0)),
                ('resp_second_type', models.IntegerField(default=0)),
                ('resp_third_type', models.IntegerField(default=0)),
                ('resp_fourth_type', models.IntegerField(default=0)),
                ('resp_another_type', models.IntegerField(default=0)),
                ('resp_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.articles')),
            ],
        ),
        migrations.CreateModel(
            name='RespToLaws',
            fields=[
                ('resp_law_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resp_first_type', models.IntegerField(default=0)),
                ('resp_second_type', models.IntegerField(default=0)),
                ('resp_third_type', models.IntegerField(default=0)),
                ('resp_fourth_type', models.IntegerField(default=0)),
                ('resp_another_type', models.IntegerField(default=0)),
                ('resp_none_type', models.IntegerField(default=0)),
                ('resp_law_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.laws')),
            ],
        ),
    ]
