# Generated by Django 5.1.7 on 2025-04-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTypes',
            fields=[
                ('accessTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('accessTypeDescr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_number', models.IntegerField()),
                ('article_title', models.CharField(max_length=100)),
                ('article_descr', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('law_id', models.IntegerField(primary_key=True, serialize=False)),
                ('law_number', models.CharField(max_length=20, unique=True, verbose_name='Номер закона')),
                ('law_title', models.CharField(max_length=400, verbose_name='Название закона')),
                ('law_date', models.DateField(verbose_name='Дата принятия')),
            ],
        ),
        migrations.CreateModel(
            name='MyClass1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data1', models.CharField(max_length=300)),
                ('data2', models.CharField(max_length=300)),
                ('data3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibilitys',
            fields=[
                ('responsibility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('responsibility_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userLogin', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleClauses',
            fields=[
                ('clause_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clause_text', models.CharField(max_length=2000)),
                ('clause_parent_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend_api.articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='article_parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend_api.laws'),
        ),
        migrations.CreateModel(
            name='RespToArticles',
            fields=[
                ('resp_article_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resp_first_type', models.IntegerField(default=0)),
                ('resp_second_type', models.IntegerField(default=0)),
                ('resp_third_type', models.IntegerField(default=0)),
                ('resp_fourth_type', models.IntegerField(default=0)),
                ('resp_another_type', models.IntegerField(default=0)),
                ('resp_none_type', models.IntegerField(default=0)),
                ('resp_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.articles')),
            ],
        ),
        migrations.CreateModel(
            name='RespToLaws',
            fields=[
                ('resp_law_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resp_first_type', models.IntegerField(default=0)),
                ('resp_second_type', models.IntegerField(default=0)),
                ('resp_third_type', models.IntegerField(default=0)),
                ('resp_fourth_type', models.IntegerField(default=0)),
                ('resp_another_type', models.IntegerField(default=0)),
                ('resp_none_type', models.IntegerField(default=0)),
                ('resp_law_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.laws')),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFirstName', models.CharField(blank=True, max_length=100)),
                ('userSecondName', models.CharField(blank=True, max_length=100)),
                ('userEmail', models.CharField(blank=True, max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.userslist')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPassword', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.userslist')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessTypeId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend_api.accesstypes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.userslist')),
            ],
        ),
    ]
