# Generated by Django 5.1.7 on 2025-03-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data1', models.CharField(max_length=300)),
                ('data2', models.CharField(max_length=300)),
                ('data3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userLogin', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userFirstName', models.CharField(max_length=100)),
                ('userSecondName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userLogin', models.CharField(max_length=100)),
            ],
        ),
    ]
