# Generated by Django 5.1.7 on 2025-03-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_login', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyClass1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data1', models.CharField(max_length=300)),
                ('data2', models.CharField(max_length=300)),
                ('data3', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='MyClass',
        ),
    ]
