# Generated by Django 5.1.7 on 2025-07-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleclauses',
            name='clause_parent_id',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='article_parent_id',
        ),
        migrations.RemoveField(
            model_name='resptoarticles',
            name='resp_article_id',
        ),
        migrations.RemoveField(
            model_name='resptolaws',
            name='resp_law_id',
        ),
        migrations.DeleteModel(
            name='MyClass2',
        ),
        migrations.DeleteModel(
            name='Responsibilitys',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='ArticleClauses',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='RespToArticles',
        ),
        migrations.DeleteModel(
            name='Laws',
        ),
        migrations.DeleteModel(
            name='RespToLaws',
        ),
    ]
