# Generated by Django 5.1.7 on 2025-03-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='userEmail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='userFirstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='userSecondName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
