# Generated by Django 5.1.7 on 2025-04-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_articles_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
