# Generated by Django 5.1.7 on 2025-07-22 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_articleclauses_clause_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
