# Generated by Django 5.1.7 on 2025-04-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_articles_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibilitys',
            name='responsibility_number',
            field=models.IntegerField(default=0),
        ),
    ]
