# Generated by Django 5.1.7 on 2025-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_responsibilitys_responsibility_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibilitys',
            name='responsibility_number',
        ),
        migrations.AddField(
            model_name='articleclauses',
            name='clause_number',
            field=models.IntegerField(default=0),
        ),
    ]
