# Generated by Django 5.1.7 on 2025-04-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_remove_responsibilitys_responsibility_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclauses',
            name='clause_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
