# Generated by Django 5.1.7 on 2025-05-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_alter_articleclauses_clause_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
