# Generated by Django 5.1.7 on 2025-05-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_alter_articles_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resptoarticles',
            name='resp_article_record_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
