# Generated by Django 5.1.7 on 2025-05-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_resptoarticles_resp_article_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resptoarticles',
            name='resp_none_type',
        ),
    ]
