# Generated by Django 5.1.7 on 2025-05-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_remove_resptoarticles_resp_none_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespToClauses',
            fields=[
                ('resp_clause_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resp_first_type', models.IntegerField(default=0)),
                ('resp_second_type', models.IntegerField(default=0)),
                ('resp_third_type', models.IntegerField(default=0)),
                ('resp_fourth_type', models.IntegerField(default=0)),
                ('resp_another_type', models.IntegerField(default=0)),
                ('resp_none_type', models.IntegerField(default=0)),
                ('resp_clause_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.articleclauses')),
            ],
        ),
    ]
