# Generated by Django 5.1.7 on 2025-05-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_resptoclauses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RespToClauses',
        ),
    ]
